### ISSUE TITLE
hope below one is profitable but why transaction not done ?

### ISSUE THREAD

**Issue by gsngsn123** [albert-garreta/arb-bot#2]
Starting epoch after waiting for 1.5489158630371094s
['LINK', 'WETH']
Reserves buying dex: [135490.45847320737, 698.9575634221709]
Reserves selling dex: [15.373139154422505, 0.07853896343901186]
Price buying dex: 193.84647303883744
Price selling dex: 195.73901260309174
Price ratio: 0.99033131137689
Buying dex index: 0
Net profit: 8.50216721152e-05 (Min: 0.07479431563201197)
Optimal borrow amount: 0.0001854967027435794

**Comment by albert-garreta** [comment]
The attribute `min_net_profits_in_usd` in bot-config.py sets a minimum amount of profit expected before attempting to do the arbitrage operation. This is set by default to 1USD, which is about 0.07489 LINK tokens (as indicated in the log). That's why the bot did not attempt arbitrage.
